<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <WindowsSdkPackageVersion>10.0.19041.87</WindowsSdkPackageVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>logo.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.0.4</Version>
    <Authors>Leon Björklund</Authors>
    <Company>Leon Björklund</Company>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Update="LICENSE;THIRD-PARTY-NOTICES.txt"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="WPlayer.Tests\**\*.cs" />
    <InternalsVisibleTo Include="WPlayer.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>

</Project>
